USE [ORG_CHART_DEV]
GO
/****** Object:  StoredProcedure [dbo].[PROC_GET_POSITION_TREE_RESTORE_VERSION]    Script Date: 27/10/2018 21:12:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Subramanian.C>
-- =============================================
ALTER PROCEDURE [dbo].[PROC_GET_POSITION_TREE_RESTORE_VERSION] 
	@VERSION AS VARCHAR(50),
	@COMPANYNAME AS VARCHAR(500),
	@OPER AS VARCHAR(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @SQLQUERY AS VARCHAR(MAX);
	DECLARE @COMPANYTB AS VARCHAR(500);
	SET @COMPANYTB = @COMPANYNAME + '_LEVELINFOS'
    IF (@OPER='LV')	SET @COMPANYTB = @COMPANYNAME + '_LEGALINFOS'

	DECLARE @QUERY  NVARCHAR(1000) = 'SELECT TOP 1 * FROM '+@COMPANYTB+' WHERE VERSION='''+@VERSION+'''', @ROWCNT INT
    EXEC Sp_executesql @QUERY
    SELECT @ROWCNT = @@ROWCOUNT
    IF @ROWCNT <= 0
    BEGIN
		SET @SQLQUERY = 'DELETE FROM '+@COMPANYTB +' WHERE VERSION='''+@VERSION+'''
                         INSERT INTO '+@COMPANYTB +' 
							SELECT * FROM BACKUP_'+@COMPANYTB+' WHERE VERSION='''+@VERSION+'''';
		EXEC(@SQLQUERY);
    END 
END


--EXEC PROC_GET_POSITION_TREE_RESTORE_VERSION '2', 'MCBITSS'