USE [ORG_CHART_DEV]
GO
/****** Object:  StoredProcedure [dbo].[PROC_SAVE_PLAYER_VERSION_TREE_OPERATIONALCHART]    Script Date: 26/09/2019 11:56:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Subramanian.C>
-- =============================================
ALTER PROCEDURE [dbo].[PROC_SAVE_PLAYER_VERSION_TREE_OPERATIONALCHART]
    @FINALYZER_VERSION AS VARCHAR(50), 
	@SOURCE_VERSION AS VARCHAR(50),
	@DESTINATION_VERSION AS VARCHAR(50),
	@POSITION_ID AS VARCHAR(50),
	@COMPANYNAME AS VARCHAR(500),
	@USERID AS VARCHAR(150),
	@USER_ROLE AS VARCHAR(150),
	@PARENT_POSITION_ID AS VARCHAR(50),
	@CHILD_FIELD AS VARCHAR(50),
	@PARENT_FIELD AS VARCHAR(50),
	@OPER VARCHAR(50)
AS
BEGIN

	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @SQLQUERY AS NVARCHAR(MAX);
	DECLARE @CHILD_VALUE AS VARCHAR(MAX);
	DECLARE @COMPANYTB AS VARCHAR(500);
	DECLARE @USERTB AS VARCHAR(500);
	DECLARE @POSITION_COST AS VARCHAR(500);
    BEGIN TRY  

		SET @COMPANYTB = @COMPANYNAME + '_' + @FINALYZER_VERSION + '_LEVELINFOS'
		SET @USERTB = 'USER_' + @USERID + '_' + @COMPANYNAME + '_LEVELINFOS';
		IF (@OPER='LV')	
		BEGIN
			SET @COMPANYTB = @COMPANYNAME + '_' + @FINALYZER_VERSION + '_LEVELINFOS'
			SET @USERTB = 'USER_' + @USERID + '_' + @COMPANYNAME + '_LEVELINFOS';
		END

		SET @SQLQUERY = 'SELECT TOP 1 @CHILD_VALUE=['+@CHILD_FIELD+'] FROM ['+@COMPANYTB+'] WHERE LEVEL_ID='''+@PARENT_POSITION_ID+''';';
		EXEC sp_executesql @SQLQUERY, N'@CHILD_VALUE NVARCHAR(1024) OUTPUT', @CHILD_VALUE OUTPUT;

		SET @SQLQUERY = N'DROP TABLE IF EXISTS ['+@USERTB+'];'
		EXEC(@SQLQUERY);

		SET @SQLQUERY = 'SELECT * INTO '+@USERTB+' FROM ['+@COMPANYTB+'] WHERE VERSION='''+@SOURCE_VERSION+''' AND BREAD_GRAM like ''%'+@POSITION_ID+'%'' AND DOTTED_LINE_FLAG=''N'';
						 UPDATE ['+@USERTB+'] SET USER_ID='''+@USERID+''', VERSION='''+@DESTINATION_VERSION+''', VERIFY_FLAG=''N'';
						 UPDATE ['+@USERTB+'] SET PARENT_LEVEL_ID='''+@PARENT_POSITION_ID+''', ['+@PARENT_FIELD+']='''+@CHILD_VALUE+''' WHERE LEVEL_ID='''+@POSITION_ID+''';
						 DELETE FROM ['+@COMPANYTB+'] WHERE VERSION='''+@DESTINATION_VERSION+''' AND LEVEL_ID IN (SELECT LEVEL_ID FROM ['+@USERTB+']);
						 INSERT INTO ['+@COMPANYTB+'] SELECT * FROM ['+@USERTB+'];'

		EXEC(@SQLQUERY);
		PRINT @SQLQUERY

		SELECT @POSITION_COST=POSITIONCOSTFIELD FROM dbo.UPLOADFILESHEADERS WHERE VERSIONNO=CAST(@FINALYZER_VERSION AS INT)
		PRINT @POSITION_COST

		-- Generate divide-by-zero error.  
		EXEC PROC_GET_TREE_OPERATIONALCHART_NOR_SOC @POSITION_COST, @USER_ROLE, @FINALYZER_VERSION, @DESTINATION_VERSION, @COMPANYNAME, @USERID, @OPER

		SELECT 'Success' Result
	END TRY  
	BEGIN CATCH  
		-- Execute error retrieval routine.  
		SELECT 
		    'Failure' Result
		    ,ERROR_NUMBER() AS ErrorNumber  
			,ERROR_SEVERITY() AS ErrorSeverity  
			,ERROR_STATE() AS ErrorState  
			,ERROR_PROCEDURE() AS ErrorProcedure  
			,ERROR_LINE() AS ErrorLine  
			,ERROR_MESSAGE() AS ErrorMessage; 
	END CATCH;
END


--EXEC PROC_SAVE_PLAYER_VERSION_TREE_OPERATIONALCHART '18', '18', '18', '10024606', 'UNHCR', 'AminAwad1', 'Finalyzer', '10024606', 'POSITION_NUMBER', 'MGR_POSTION', 'OV'
--DELETE FROM MCBITSS_LevelInfos WHERE VERIFY_FLAG='N'
