USE [ORG_CHART_DEV]
GO
/****** Object:  StoredProcedure [dbo].[PROC_SAVE_PLAYER_COMPLETED_VERSION]    Script Date: 26/10/2018 08:11:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Subramanian.C>
-- =============================================
ALTER PROCEDURE [dbo].[PROC_SAVE_PLAYER_COMPLETED_VERSION] 
	@SOURCE_VERSION AS VARCHAR(50),
	@OPER AS VARCHAR(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @SQLQUERY AS NVARCHAR(MAX);
	DECLARE @COMPANYTB AS VARCHAR(500);
	DECLARE @USERTB AS VARCHAR(500);

	DECLARE @DESTINATION_VERSION AS VARCHAR(500);
	DECLARE @COMPANYNAME AS VARCHAR(500);
	DECLARE @USERID AS VARCHAR(500);
	SELECT TOP 1 @DESTINATION_VERSION=VERSIONNO, @COMPANYNAME=CompanyName, @USERID=USERID FROM UploadFilesHeaders WHERE Role ='Finalyzer' ORDER BY CreatedDate DESC
	
	SET @COMPANYTB = @COMPANYNAME + '_LEVELINFOS';
	SET @USERTB = @USERID + '_LEVELINFOS';
	IF (@OPER='LV') 
	BEGIN 
	    SET @COMPANYTB = @COMPANYNAME + '_LEGALINFOS';
		SET @USERTB = @USERID + '_LEGALINFOS';
	END

	SET @SQLQUERY = 'DROP TABLE IF EXISTS ['+@USERTB+'];
	                 SELECT * INTO '+@USERTB+' FROM ['+@COMPANYTB+'] WHERE VERSION='''+@SOURCE_VERSION+''' AND VERIFY_FLAG like ''N'';
					 UPDATE ['+@USERTB+'] SET VERIFY_FLAG=''Y'', VERSION='''+@DESTINATION_VERSION+''' WHERE VERIFY_FLAG=''N'' AND VERSION='''+@SOURCE_VERSION+''';
	                 DELETE FROM ['+@COMPANYTB+'] WHERE VERSION='''+@DESTINATION_VERSION+''' AND LEVEL_ID IN (SELECT LEVEL_ID FROM ['+@USERTB+']);
	                 INSERT INTO ['+@COMPANYTB+'] SELECT * FROM ['+@USERTB+'];
					 UPDATE ['+@COMPANYTB+'] SET VERIFY_FLAG=''Y'' WHERE VERIFY_FLAG=''N'' AND VERSION='''+@SOURCE_VERSION+''';'
					 
	EXEC(@SQLQUERY);

	EXEC PROC_GET_TREE_OPERATIONALCHART_NOR_SOC 'Finalyzer', @DESTINATION_VERSION, @COMPANYNAME, @USERID, @OPER 
END

--EXEC PROC_SAVE_PLAYER_COMPLETED_VERSION '2'
--DELETE FROM MCBITSS_LevelInfos WHERE VERIFY_FLAG='N'
