USE [ORG_CHART_DEV]
GO
/****** Object:  StoredProcedure [dbo].[PROC_SAVE_FINALYZER_COMPLETED_VERSION]    Script Date: 26/10/2018 08:12:40 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Subramanian.C>
-- =============================================
ALTER PROCEDURE [dbo].[PROC_SAVE_FINALYZER_COMPLETED_VERSION] 
	@SOURCE_VERSION AS VARCHAR(50),
	@OPER AS VARCHAR(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @SQLQUERY AS NVARCHAR(MAX);
	DECLARE @COMPANYTB AS VARCHAR(500);
	DECLARE @USERTB AS VARCHAR(500);

	DECLARE @DESTINATION_VERSION AS VARCHAR(500);
	DECLARE @COMPANYNAME AS VARCHAR(500);
	DECLARE @USERID AS VARCHAR(500);
	SELECT TOP 1 @DESTINATION_VERSION=VERSIONNO, @COMPANYNAME=CompanyName, @USERID=USERID FROM UploadFilesHeaders WHERE Role ='Finalyzer' ORDER BY CreatedDate DESC
	
	SET @COMPANYTB = @COMPANYNAME + '_LEVELINFOS';
	SET @USERTB = @USERID + '_LEVELINFOS';
	IF (@OPER='LV') 
	BEGIN 
	    SET @COMPANYTB = @COMPANYNAME + '_LEGALINFOS';
		SET @USERTB = @USERID + '_LEGALINFOS';
	END

	SET @SQLQUERY = 'DROP TABLE IF EXISTS ['+@USERTB+'];
	                 SELECT * INTO '+@USERTB+' FROM ['+@COMPANYTB+'] WHERE VERSION='''+@SOURCE_VERSION+''';
					 UPDATE ['+@USERTB+'] SET USER_ID='''+@COMPANYNAME+''', VERSION=''199999'';
	                 DELETE FROM ['+@COMPANYTB+'] WHERE USER_ID='''+@COMPANYNAME+''';
	                 INSERT INTO ['+@COMPANYTB+'] SELECT * FROM ['+@USERTB+'];'
					 
	EXEC(@SQLQUERY);
END

--EXEC PROC_SAVE_FINALYZER_COMPLETED_VERSION '1'
--DELETE FROM MCBITSS_LevelInfos WHERE VERIFY_FLAG='N'
