USE [ORG_CHART_DEV]
GO
/****** Object:  StoredProcedure [dbo].[PROC_GET_POSITION_TREE_BACKUP_VERSION]    Script Date: 26/10/2018 08:25:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Subramanian.C>
-- =============================================
ALTER PROCEDURE [dbo].[PROC_GET_POSITION_TREE_BACKUP_VERSION] 
	@VERSION AS VARCHAR(50),
	@COMPANYNAME AS VARCHAR(500),
	@OPER AS VARCHAR(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @SQLQUERY AS VARCHAR(MAX);
	DECLARE @COMPANYTB AS VARCHAR(500);
	IF (@OPER='OV')
	BEGIN
		SET @COMPANYTB = @COMPANYNAME + '_LEVELINFOS'

		SET @SQLQUERY = 'DELETE FROM BACKUP_'+@COMPANYTB +' WHERE VERSION='''+@VERSION+'''
						 INSERT INTO BACKUP_'+@COMPANYTB +' 
							SELECT * FROM '+@COMPANYTB+' WHERE VERSION='''+@VERSION+'''';
		EXEC(@SQLQUERY);

		SET @SQLQUERY = 'SELECT * 
							FROM '+@COMPANYTB+' WHERE VERSION='''+@VERSION+'''
							ORDER BY PARENT_LEVEL_ID DESC';
		EXEC(@SQLQUERY);
	END
	ELSE
	BEGIN
		IF (@OPER='LV')
		BEGIN
			SET @COMPANYTB = @COMPANYNAME + '_LEGALINFOS'

			SET @SQLQUERY = 'DELETE FROM BACKUP_'+@COMPANYTB +' WHERE VERSION='''+@VERSION+'''
							 INSERT INTO BACKUP_'+@COMPANYTB +' 
								SELECT * FROM '+@COMPANYTB+' WHERE VERSION='''+@VERSION+'''';
			EXEC(@SQLQUERY);

			SET @SQLQUERY = 'SELECT * 
								FROM '+@COMPANYTB+' WHERE VERSION='''+@VERSION+'''
								ORDER BY PARENT_LEVEL_ID DESC';
			EXEC(@SQLQUERY);
		END
	END
END


--EXEC PROC_GET_POSITION_TREE_BACKUP_VERSION '2', 'MCBITSS'