USE [ORG_CHART_DEV]
GO
/****** Object:  StoredProcedure [dbo].[PROC_SAVE_PLAYER_VERSION_TREE_OPERATIONALCHART]    Script Date: 26/10/2018 08:08:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Subramanian.C>
-- =============================================
ALTER PROCEDURE [dbo].[PROC_SAVE_PLAYER_VERSION_TREE_OPERATIONALCHART] 
	@SOURCE_VERSION AS VARCHAR(50),
	@DESTINATION_VERSION AS VARCHAR(50),
	@POSITION_ID AS VARCHAR(50),
	@COMPANYNAME AS VARCHAR(500),
	@USERID AS VARCHAR(50),
	@PARENT_POSITION_ID AS VARCHAR(50),
	@CHILD_FIELD AS VARCHAR(50),
	@PARENT_FIELD AS VARCHAR(50),
	@OPER VARCHAR(50)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @SQLQUERY AS NVARCHAR(MAX);
	DECLARE @CHILD_VALUE AS VARCHAR(MAX);
	DECLARE @COMPANYTB AS VARCHAR(500);
	DECLARE @USERTB AS VARCHAR(500);

	SET @COMPANYTB = @COMPANYNAME + '_LEVELINFOS';
    SET @USERTB = @USERID + '_LEVELINFOS';
	IF (@OPER='LV') 
	BEGIN 
	    SET @COMPANYTB = @COMPANYNAME + '_LEGALINFOS';
		SET @USERTB = @USERID + '_LEGALINFOS';
	END

	SET @SQLQUERY = 'SELECT TOP 1 @CHILD_VALUE=['+@CHILD_FIELD+'] FROM ['+@COMPANYTB+'] WHERE LEVEL_ID='''+@PARENT_POSITION_ID+''';';
    EXEC sp_executesql @SQLQUERY, N'@CHILD_VALUE NVARCHAR(1024) OUTPUT', @CHILD_VALUE OUTPUT;

	SET @SQLQUERY = 'DROP TABLE IF EXISTS ['+@USERTB+'];
	                 SELECT * INTO '+@USERTB+' FROM ['+@COMPANYTB+'] WHERE VERSION='''+@SOURCE_VERSION+''' AND BREAD_GRAM like ''%'+@POSITION_ID+'%'';
					 UPDATE ['+@USERTB+'] SET USER_ID='''+@USERID+''', VERSION='''+@DESTINATION_VERSION+''', VERIFY_FLAG=''N'';
					 UPDATE ['+@USERTB+'] SET PARENT_LEVEL_ID='''+@PARENT_POSITION_ID+''', '+@PARENT_FIELD+'='''+@CHILD_VALUE+''' WHERE LEVEL_ID='''+@POSITION_ID+''';
					 DELETE FROM ['+@COMPANYTB+'] WHERE VERSION='''+@DESTINATION_VERSION+''' AND LEVEL_ID IN (SELECT LEVEL_ID FROM ['+@USERTB+']);
					 INSERT INTO ['+@COMPANYTB+'] SELECT * FROM ['+@USERTB+'];'

	EXEC(@SQLQUERY);
	PRINT @SQLQUERY

	EXEC PROC_GET_TREE_OPERATIONALCHART_NOR_SOC 'Player', @DESTINATION_VERSION, @COMPANYNAME, @USERID, @OPER 
END


--EXEC PROC_SAVE_PLAYER_VERSION_TREE_OPERATIONALCHART '2', '2', '100009', 'MCBITSS', 'SUBBUCITTIBABU', '100004', 'FULL_NAME', 'SUP_DISPLAY_NAME', 'LV'
--DELETE FROM MCBITSS_LevelInfos WHERE VERIFY_FLAG='N'
