USE [ORG_CHART_DEV]
GO

DELETE FROM MENAOrgChartData
INSERT INTO MENAOrgChartData
SELECT [MSRP_EMPLID]
      ,[MSRP_NAME_PREFIX]
      ,[MSRP_NAME]
      ,[MSRP_LAST_NAME]
      ,[MSRP_MIDDLE_NAME]
      ,[MSRP_FIRST_NAME]
      ,[MSRP_UN_INDEX_NBR]
      ,[MSRP_LOCATION]
      ,[MSRP_LOCATION_DESCR]
      ,[MSRP_COUNTRY_CODE]
      ,[MSRP_COUNTRY]
      ,[MSRP_PERSONAL_GRADE]
      ,[MSRP_EMAILID]
      ,[MSRP_GENDER]
      ,[MSRP_DEPTID]
      ,[MSRP_DIVISION]
      ,[MSRP_POSITION_TITLE]
      ,[MSRP_JOB_TITLE]
      ,[MSRP_FUNC_GP_L1_DESCR]
      ,[MSRP_POSITION_NBR]
      ,[MSRP_FUNC_GP_L2_DESCR]
      ,[MSRP_FUNC_GP_L3_DESCR]
      ,[MSRP_POSITION_GRADE]
      ,[MSRP_FUNDING]
      ,[MSRP_EMPLOYEE_TYPE]
      ,[MSRP_SUP_NAME]
      ,[MSRP_LEVEL_NO]
      ,[MSRP_LEVEL_ID]
      ,[MSRP_PARENT_LEVEL_ID]
  FROM [MENAOrgChartDataTemp]

DECLARE @LEVEL_ID AS INT = 10001339;
DECLARE @INITIAL_LEVEL_ID AS INT = 10001339;
DECLARE @PARENT_LEVEL_ID AS INT = 999999;
DECLARE @MSRP_LEVEL_ID AS VARCHAR(100)='';
DECLARE @MSRP_PARENT_LEVEL_ID AS VARCHAR(100)='';
DECLARE @MSRP_SUP_NAME AS VARCHAR(100)='';
DECLARE @MSRP_COUNTRY AS VARCHAR(100)='UNHCR';
DECLARE @MSRP_FUNC_GP_L1_DESCR AS VARCHAR(500)='';

DECLARE @REMOVE_COUNTRY TABLE(COUNTRY VARCHAR(100));
INSERT INTO @REMOVE_COUNTRY VALUES('POLAND');
INSERT INTO @REMOVE_COUNTRY VALUES('FRANCE');
INSERT INTO @REMOVE_COUNTRY VALUES('BELGIUM');

-- Top level node
INSERT INTO MENAOrgChartData (
     [MSRP_NAME]
	,[MSRP_COUNTRY]
	,[MSRP_PERSONAL_GRADE]
	,[MSRP_FUNC_GP_L1_DESCR]
	,[MSRP_POSITION_NBR]
	,[MSRP_LEVEL_NO]
	,[MSRP_LEVEL_ID]
	,[MSRP_PARENT_LEVEL_ID]
)
VALUES (
	'Amin Awad',
	'RRC Syria Situation',
	'D2',
	'Director',
	@LEVEL_ID,
	'0',
	@LEVEL_ID,
	@PARENT_LEVEL_ID
)

SET @PARENT_LEVEL_ID=@LEVEL_ID;
SET @LEVEL_ID=20000000;

DECLARE MENAORGCHART_COUNTRY_CURSOR CURSOR LOCAL FORWARD_ONLY FOR SELECT DISTINCT MSRP_COUNTRY 
                                                                    FROM MENAOrgChartDataTemp  
																	WHERE MSRP_COUNTRY NOT IN (SELECT COUNTRY FROM @REMOVE_COUNTRY)
OPEN MENAORGCHART_COUNTRY_CURSOR  
FETCH NEXT FROM MENAORGCHART_COUNTRY_CURSOR INTO  @MSRP_COUNTRY
WHILE @@FETCH_STATUS = 0  
BEGIN  

	INSERT INTO MENAOrgChartData (
         [MSRP_NAME]
		,[MSRP_COUNTRY]
		,[MSRP_PERSONAL_GRADE]
		,[MSRP_FUNC_GP_L1_DESCR]
		,[MSRP_POSITION_NBR]
		,[MSRP_LEVEL_NO]
		,[MSRP_LEVEL_ID]
		,[MSRP_PARENT_LEVEL_ID]
	)
	VALUES (
	    @MSRP_COUNTRY,
		@MSRP_COUNTRY,
		'',
		@MSRP_COUNTRY,
		@LEVEL_ID,
		'1',
		@LEVEL_ID,
		@INITIAL_LEVEL_ID
	)

	SET @PARENT_LEVEL_ID=@LEVEL_ID;
	SET @LEVEL_ID=@LEVEL_ID + 1;	

	DECLARE MENAORGCHART_DEPARTMENT_CURSOR CURSOR LOCAL 
	       FORWARD_ONLY FOR SELECT DISTINCT MSRP_FUNC_GP_L1_DESCR 
		                       FROM MENAOrgChartDataTemp 
							   WHERE MSRP_COUNTRY=@MSRP_COUNTRY AND (MSRP_SUP_NAME='NULL' OR MSRP_SUP_NAME IS NULL)
	OPEN MENAORGCHART_DEPARTMENT_CURSOR  
	FETCH NEXT FROM MENAORGCHART_DEPARTMENT_CURSOR INTO @MSRP_FUNC_GP_L1_DESCR
	WHILE @@FETCH_STATUS = 0  
	BEGIN  
		INSERT INTO MENAOrgChartData (
           [MSRP_NAME]
		  ,[MSRP_COUNTRY]
		  ,[MSRP_PERSONAL_GRADE]
		  ,[MSRP_FUNC_GP_L1_DESCR]
		  ,[MSRP_POSITION_NBR]
		  ,[MSRP_LEVEL_NO]
		  ,[MSRP_LEVEL_ID]
		  ,[MSRP_PARENT_LEVEL_ID]
		)
	    VALUES (
			@MSRP_FUNC_GP_L1_DESCR+'( '+@MSRP_COUNTRY +' )',
			@MSRP_COUNTRY,
			'',
			@MSRP_FUNC_GP_L1_DESCR,
			@LEVEL_ID,
			'2',
			@LEVEL_ID,
			@PARENT_LEVEL_ID
	    )
			
		PRINT @MSRP_FUNC_GP_L1_DESCR	
		UPDATE MENAOrgChartData
		   SET MSRP_SUP_NAME=@MSRP_FUNC_GP_L1_DESCR+'( '+@MSRP_COUNTRY +' )', 
		       MSRP_LEVEL_ID=MSRP_SERIELNO+30000000, 
			   MSRP_PARENT_LEVEL_ID=@LEVEL_ID
		   WHERE MSRP_FUNC_GP_L1_DESCR = @MSRP_FUNC_GP_L1_DESCR AND 
		         MSRP_COUNTRY = @MSRP_COUNTRY AND 
				 MSRP_NAME <> @MSRP_COUNTRY AND 
				 (MSRP_SUP_NAME='NULL' OR MSRP_SUP_NAME IS NULL)

		SET @LEVEL_ID=@LEVEL_ID + 1;

		FETCH NEXT FROM MENAORGCHART_DEPARTMENT_CURSOR INTO @MSRP_FUNC_GP_L1_DESCR
	END  
	CLOSE MENAORGCHART_DEPARTMENT_CURSOR  
	DEALLOCATE MENAORGCHART_DEPARTMENT_CURSOR  

	UPDATE MENAOrgChartData 
	  SET MSRP_LEVEL_ID=MSRP_SERIELNO+30000000 
	  WHERE MSRP_LEVEL_ID IS NULL AND MSRP_COUNTRY=@MSRP_COUNTRY

	DECLARE MENAORGCHART_SUP_NAME_CURSOR CURSOR LOCAL 
	       FORWARD_ONLY FOR SELECT DISTINCT MSRP_SUP_NAME 
		                       FROM MENAOrgChartData 
							   WHERE MSRP_COUNTRY=@MSRP_COUNTRY AND MSRP_PARENT_LEVEL_ID IS NULL
	OPEN MENAORGCHART_SUP_NAME_CURSOR  
	FETCH NEXT FROM MENAORGCHART_SUP_NAME_CURSOR INTO  @MSRP_SUP_NAME
	WHILE @@FETCH_STATUS = 0  
	BEGIN  		 
		SET @MSRP_PARENT_LEVEL_ID=NULL;
		SELECT @MSRP_PARENT_LEVEL_ID=CAST((MSRP_SERIELNO+30000000) AS VARCHAR(100)) 
		   FROM MENAOrgChartData 
		   WHERE TRIM(MSRP_NAME)=TRIM(@MSRP_SUP_NAME)
		IF (@MSRP_PARENT_LEVEL_ID IS NULL) SET @MSRP_PARENT_LEVEL_ID='99999999';

		PRINT @MSRP_SUP_NAME	
		UPDATE MENAOrgChartData
		   SET MSRP_PARENT_LEVEL_ID=@MSRP_PARENT_LEVEL_ID
		   WHERE MSRP_SUP_NAME=@MSRP_SUP_NAME AND MSRP_COUNTRY=@MSRP_COUNTRY AND MSRP_NAME <> @MSRP_COUNTRY

		FETCH NEXT FROM MENAORGCHART_SUP_NAME_CURSOR INTO @MSRP_SUP_NAME
	END  
	CLOSE MENAORGCHART_SUP_NAME_CURSOR  
	DEALLOCATE MENAORGCHART_SUP_NAME_CURSOR  

	DECLARE MENAORGCHART_PARENT_ID_CURSOR CURSOR LOCAL 
	       FORWARD_ONLY FOR SELECT DISTINCT MSRP_COUNTRY, MSRP_FUNC_GP_L1_DESCR  
		                       FROM MENAOrgChartData 
							   WHERE MSRP_COUNTRY=@MSRP_COUNTRY AND MSRP_PARENT_LEVEL_ID = '99999999'
	OPEN MENAORGCHART_PARENT_ID_CURSOR  
	FETCH NEXT FROM MENAORGCHART_PARENT_ID_CURSOR INTO  @MSRP_COUNTRY, @MSRP_FUNC_GP_L1_DESCR
	WHILE @@FETCH_STATUS = 0  
	BEGIN  		 

	    SELECT @PARENT_LEVEL_ID='10001339';
	    SELECT @PARENT_LEVEL_ID=MSRP_LEVEL_ID
			FROM MENAOrgChartData 
			WHERE MSRP_COUNTRY=@MSRP_COUNTRY AND MSRP_PARENT_LEVEL_ID='10001339'

		INSERT INTO MENAOrgChartData (
           [MSRP_NAME]
		  ,[MSRP_COUNTRY]
		  ,[MSRP_PERSONAL_GRADE]
		  ,[MSRP_FUNC_GP_L1_DESCR]
		  ,[MSRP_POSITION_NBR]
		  ,[MSRP_LEVEL_NO]
		  ,[MSRP_LEVEL_ID]
		  ,[MSRP_PARENT_LEVEL_ID]
		)
	    VALUES (
			@MSRP_FUNC_GP_L1_DESCR+'( '+@MSRP_COUNTRY +' )',
			@MSRP_COUNTRY,
			'',
			@MSRP_FUNC_GP_L1_DESCR,
			@LEVEL_ID,
			'2',
			@LEVEL_ID,
			@PARENT_LEVEL_ID
	    )
			
		PRINT @MSRP_COUNTRY+' '+@MSRP_FUNC_GP_L1_DESCR	
		UPDATE MENAOrgChartData
		   SET MSRP_PARENT_LEVEL_ID=@LEVEL_ID, MSRP_SUP_NAME=@MSRP_FUNC_GP_L1_DESCR+'( '+@MSRP_COUNTRY +' )'
		   WHERE MSRP_COUNTRY=@MSRP_COUNTRY AND MSRP_FUNC_GP_L1_DESCR = @MSRP_FUNC_GP_L1_DESCR AND MSRP_PARENT_LEVEL_ID='99999999';

	    SET @LEVEL_ID=@LEVEL_ID + 1;

		FETCH NEXT FROM MENAORGCHART_PARENT_ID_CURSOR INTO  @MSRP_COUNTRY, @MSRP_FUNC_GP_L1_DESCR
	END  
	CLOSE MENAORGCHART_PARENT_ID_CURSOR  
	DEALLOCATE MENAORGCHART_PARENT_ID_CURSOR  

	FETCH NEXT FROM MENAORGCHART_COUNTRY_CURSOR INTO  @MSRP_COUNTRY
END  
CLOSE MENAORGCHART_COUNTRY_CURSOR  
DEALLOCATE MENAORGCHART_COUNTRY_CURSOR  

SELECT *
   FROM MENAOrgChartData 
   WHERE MSRP_LEVEL_ID IS NOT NULL
   ORDER BY CAST(MSRP_PARENT_LEVEL_ID AS INT) , CAST(MSRP_LEVEL_ID as INT)

--SELECT MSRP_LEVEL_ID, MSRP_PARENT_LEVEL_ID, MSRP_LEVEL_NO, MSRP_NAME, MSRP_SUP_NAME, MSRP_COUNTRY, MSRP_FUNC_GP_L1_DESCR 
--   FROM MENAOrgChartData 
--   WHERE MSRP_LEVEL_ID IS NOT NULL
--   ORDER BY CAST(MSRP_PARENT_LEVEL_ID AS INT) , CAST(MSRP_LEVEL_ID as INT)


