DECLARE @REMOVE_COUNTRY TABLE(COUNTRY VARCHAR(100));
INSERT INTO @REMOVE_COUNTRY VALUES('POLAND');
INSERT INTO @REMOVE_COUNTRY VALUES('FRANCE');
INSERT INTO @REMOVE_COUNTRY VALUES('BELGIUM');

DECLARE @MSRP_COUNTRY AS VARCHAR(100);

DECLARE MENAORGCHART_COUNTRY_CURSOR CURSOR LOCAL FORWARD_ONLY FOR SELECT DISTINCT MSRP_LEVEL_ID 
                                                                    FROM MENAOrgChartData  
																	WHERE MSRP_COUNTRY NOT IN (SELECT COUNTRY FROM @REMOVE_COUNTRY)
OPEN MENAORGCHART_COUNTRY_CURSOR  
FETCH NEXT FROM MENAORGCHART_COUNTRY_CURSOR INTO  @MSRP_COUNTRY
WHILE @@FETCH_STATUS = 0  
BEGIN  
    PRINT @MSRP_COUNTRY;

	;WITH RCTE AS
	(
		SELECT  MSRP_PARENT_LEVEL_ID, MSRP_LEVEL_ID, 1 AS Lvl FROM MENAOrgChartData WHERE MSRP_LEVEL_ID=@MSRP_COUNTRY
		UNION ALL
		SELECT rh.MSRP_PARENT_LEVEL_ID, rc.MSRP_LEVEL_ID, Lvl+1 AS Lvl 
		FROM dbo.MENAOrgChartData rh
		INNER JOIN RCTE rc ON rh.MSRP_LEVEL_ID = rc.MSRP_PARENT_LEVEL_ID
	)
	,CTE_RN AS 
	(
		SELECT *, ROW_NUMBER() OVER (PARTITION BY r.MSRP_LEVEL_ID ORDER BY r.Lvl DESC) RN
		FROM RCTE r

	)
	SELECT r.MSRP_LEVEL_ID, r.MSRP_PARENT_LEVEL_ID
	FROM CTE_RN r
	--WHERE RN =1

	FETCH NEXT FROM MENAORGCHART_COUNTRY_CURSOR INTO  @MSRP_COUNTRY
END  
CLOSE MENAORGCHART_COUNTRY_CURSOR  
DEALLOCATE MENAORGCHART_COUNTRY_CURSOR  


;WITH RCTE AS
(
    SELECT  MSRP_PARENT_LEVEL_ID, MSRP_LEVEL_ID, 1 AS Lvl FROM MENAOrgChartData WHERE MSRP_LEVEL_ID='30000219'
    UNION ALL
    SELECT rh.MSRP_PARENT_LEVEL_ID, rc.MSRP_LEVEL_ID, Lvl+1 AS Lvl 
    FROM dbo.MENAOrgChartData rh
    INNER JOIN RCTE rc ON rh.MSRP_LEVEL_ID = rc.MSRP_PARENT_LEVEL_ID
)
,CTE_RN AS 
(
    SELECT *, ROW_NUMBER() OVER (PARTITION BY r.MSRP_LEVEL_ID ORDER BY r.Lvl DESC) RN
    FROM RCTE r

)
SELECT r.MSRP_LEVEL_ID, r.MSRP_PARENT_LEVEL_ID
FROM CTE_RN r
--WHERE RN =1